- name: demo on condition
  hosts: localhost
  connection: local
  tasks:



    - name: Get reminder
      ansible.builtin.shell: echo $(({{number}}%2))
      register: reminder

    - name: Print Even Number
      ansible.builtin.debug:
        msg: Number {{ number }} is even
      when: reminder.stdout == "0"