- name: demo on condition
  hosts: localhost
  connection: local
  tasks:
    - name: print OS Redhat
      ansible.builtin.debug:
        msg: Redhat
      when: os == "redhat"

    - name: print OS ubuntu
      ansible.builtin.debug:
        msg: ubuntu
      when: os == "ubuntu"