- name: Demo on loops
  hosts: localhost
  connection: local
  tasks:
    - name: print fruit
      ansible.builtin.debug:
        msg: fruit name - {{ item }}
      loop:
        - apple
        - banana
    - name: print fruit & qty
      ansible.builtin.debug:
        msg: fruit name - {{ item.name }},qty  - {{ item.qty }}
      loop:
        - {name: apple, qty: 20}
        - {name: banana, qty: 30}
      when: item.qty >25