- name: demo on handlers
  hosts: localhost
  connection: local
  tasks:
    - name: list
      ansible.builtin.shell: ls
      notify:
        - say hello

  handlers:
    - name: say hello
      ansible.builtin.debug:
        msg: hello, i am notify
