- name: print URL
  ansible.builtin.debug:
    msg: URL - {{ URL }}

- name: print hello
  ansible.builtin.debug:
    msg: hello

- name: Print EXAMPLE
  ansible.builtin.debug:
    msg: EXAMPLE - {{ EXAMPLE }}